services:
  django: &django
    image: zethoc/bm_quotes_api
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres-local
    ports:
      - "8000:8000"   
    command: /start

  bemanager-auth:
    image: danielcaicedo8991/bemanager-auth:v1.0
    ports:
      - "3030:3030"
