services:
  apigateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    volumes:
      - .:/app
    depends_on:
      - combined-reservations
      - hotel-reservations 

  combined-reservations:
    image: nhuertasuv/ipyd-combined-reservations
    ports: 
      - "8420:8420"   

  hotel-reservations:
    image: camilom959/hotel-reservations-service
    ports: 
      - "3000:3000"
  
  flight-reservations:
    image: cristiangabriel/flight-reservations-service
    ports: 
      - "9090:9090"
