services:
  bemanager-quotes:
    image: zethoc/bm_quotes_api    
    env_file:    
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"   
    command: /start

  bemanager-auth:
    image: danielcaicedo8991/bemanager-auth:v1.0
    ports:
      - "3030:3030"

  # bemanager-clients:
  #   image: anborja/bm_clients_api
  #   ports: 
  #     - "8000:8080"    


