services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: ms_quotes_local_django
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres-local
    ports:
      - "8000:8000"   
    command: /start
    
  bemanager-auth:
  image: danielcaicedo8991/bemanager-auth:v1.0
  ports:
    - "3030:3030"
